function_parameter_count: 8
identifier_name:
  excluded:
    - id
    - ok
excluded:
  - Tests
  - DerivedData
  - .build
indentation_width:
  indentation_width: 2
disabled_rules:
  - line_length
  - nesting
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - closure_body_length
  - file_length
custom_rules:
  payload_disallow: # 1
    name: "Payload Disallowed" # 2
    regex: '\w+Payload' # 3
    capture_group: 0 # 4
    message: "Do not use Payload for identifier." # 5
    severity: error # 6