name: IPSWDownloads
options:
  preGenCommand: ./Scripts/generate.sh
settings:
  LINT_MODE: ${LINT_MODE}
packages:
  IPSWDownloads:
    path: .
aggregateTargets:
  Lint:
    buildScripts:
      - path: Scripts/lint.sh
        name: Lint
        basedOnDependencyAnalysis: false
    schemes: {}